name: vectoradd_jax
version: "1.0.0"
description: |
  Tesseract that adds/subtracts two vectors. Uses jax internally.

build_config:
  target_platform: "native"
  # package_data: []
  # custom_build_steps: []
