name: Run example notebooks

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - examples/**

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # NOTE: If bumping the minimum Python version here, also do it in
        # ruff.toml, setup.py and other CI files as well.

        # test with oldest supported Python version only (for slow tests)
        python-version: ["3.10"]

        example:
          - simple
          - cfd
          - fem-shapeopt

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore UV environment
        run: cp production.uv.lock uv.lock

      - name: Install system requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y libosmesa6

      - name: Install dev requirements
        run: |
          uv sync --extra dev --frozen

      - name: Run example
        working-directory: examples/${{matrix.example}}
        run: |
          uv pip install jupyter
          uv run --no-sync jupyter nbconvert --to notebook --execute demo.ipynb
